### ISSUE TITLE
Git subfmodule approach and zip file download

### ISSUE THREAD

**Issue by felixhayashi** [kixam/TW5-moment.js#1]
Hi @kixam 

The submodule approach you are using to reference a fixed commit of moment.js repo (and you also suggested for TiddlyMap) is very sweet but has the drawback that a generated zip file of your plugin will not contain the actual library. This means that users that use it with node.js will only discover an empty folder "moment". Not sure if they'll understand how to handle this case, so maybe it is better to do it the primitive way (manually including a snapshot)? Otherwise, please include a hint that the Zip-Method cannot be used and that cloning needs the recursive flag (`--recursive`).

-Felix

**Comment by kixam** [comment]
Hi @felixhayashi 

I do not test my plugins in node.js. I know I should, but I do not understand it enough yet, and do not care enough.

Anyway, you are right, I should at least describe how to clone a fully functional repo.

**Comment by kixam** [comment]
all done (except for testing in node.js, but I assume it will be okay now)

**Comment by felixhayashi** [comment]
Great, thanks for adding the info to the readme.
